# Generated by Django 4.2.16 on 2024-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedpost',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='savedpost',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
